name: Bug report
description: File a bug report.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug.
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: "How can this bug be reproduced?"
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: report-information
    attributes:
      label: Report information
      description: "Copy and paste the program 'Report information' output."
      placeholder: |
        Report information:
        ```python
        DeobfuscatorHelper_getString(
            -123,
            [
                "\\u0006REPORT",
            ],
        )
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Fedora 41
          - **Python**: 3.13.0
      value: |
        - OS:
        - Python:
      render: markdown
    validations:
      required: false
